$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$binDir = Join-Path $repoRoot "bin"
$fsDir = Join-Path $repoRoot "web\fs"
$buildDir = Join-Path $repoRoot "web\build"
$aliasFile = Join-Path $buildDir "wasm_path_aliases.inc"
$jhSource = Join-Path $binDir "JHOnlineData"
$jhDest = Join-Path $fsDir "JHOnlineData"

if (-not (Test-Path $binDir)) {
    throw "missing bin directory: $binDir"
}

$webDir = (Resolve-Path (Join-Path $repoRoot "web")).Path
if ($fsDir.StartsWith($webDir, [System.StringComparison]::OrdinalIgnoreCase) -ne $true) {
    throw "refusing to recreate unexpected path: $fsDir"
}

if (Test-Path $fsDir) {
    Remove-Item -LiteralPath $fsDir -Recurse -Force
}

New-Item -ItemType Directory -Force -Path (Join-Path $fsDir "CBE") | Out-Null
New-Item -ItemType Directory -Force -Path $buildDir | Out-Null

Copy-Item -LiteralPath (Join-Path $binDir "font_gb.uc3") -Destination (Join-Path $fsDir "font_gb.uc3") -Force
Copy-Item -LiteralPath (Join-Path $binDir "font_16_sky.uc3") -Destination (Join-Path $fsDir "font_16_sky.uc3") -Force
Copy-Item -LiteralPath (Join-Path $binDir "gb16.uc2.uc3") -Destination (Join-Path $fsDir "gb16.uc2.uc3") -Force

$jianghuName = ([char]0x6c5f).ToString() + ([char]0x6e56).ToString() + "OL"
$sourceCbe = Join-Path $binDir ("CBE\" + $jianghuName + ".cbe")
$destCbe = Join-Path $fsDir ("CBE\" + $jianghuName + ".CBE")
Copy-Item -LiteralPath $sourceCbe -Destination $destCbe -Force

$gbkEncoding = [System.Text.Encoding]::GetEncoding(936)
$utf8Encoding = [System.Text.Encoding]::UTF8
$aliasEntries = New-Object System.Collections.Generic.List[string]
$aliasSeen = @{}

function ConvertTo-CStringBytes([byte[]]$bytes) {
    $parts = foreach ($b in $bytes) {
        "\" + [Convert]::ToString($b, 8).PadLeft(3, "0")
    }
    return """" + (($parts -join "")) + """"
}

function Add-WasmPathAlias([string]$relativePath) {
    $normalized = $relativePath.Replace("\", "/")
    if ($aliasSeen.ContainsKey($normalized)) {
        return
    }
    $aliasSeen[$normalized] = $true
    $gbkLiteral = ConvertTo-CStringBytes $gbkEncoding.GetBytes($normalized)
    $utf8Literal = ConvertTo-CStringBytes $utf8Encoding.GetBytes($normalized)
    $aliasEntries.Add("    { $gbkLiteral, $utf8Literal },") | Out-Null
}

function Add-WasmPathWithParents([string]$relativePath) {
    $normalized = $relativePath.Replace("\", "/")
    $parts = $normalized.Split("/")
    if ($parts.Length -gt 1) {
        $current = ""
        for ($i = 0; $i -lt ($parts.Length - 1); $i++) {
            if ($current.Length -eq 0) {
                $current = $parts[$i]
            } else {
                $current = $current + "/" + $parts[$i]
            }
            Add-WasmPathAlias $current
        }
    }
    Add-WasmPathAlias $normalized
}

Add-WasmPathAlias "CBE"
Add-WasmPathAlias ("CBE/" + $jianghuName + ".CBE")

if (Test-Path $jhSource) {
    New-Item -ItemType Directory -Force -Path $jhDest | Out-Null
    Add-WasmPathAlias "JHOnlineData"
    $skipExtensions = @(".id0", ".id1", ".id2", ".i64", ".nam", ".til")
    $jhRoot = (Resolve-Path $jhSource).Path
    Get-ChildItem -LiteralPath $jhSource -Recurse -File |
        Where-Object { $skipExtensions -notcontains $_.Extension } |
        ForEach-Object {
            $relative = $_.FullName.Substring($jhRoot.Length).TrimStart("\")
            $dest = Join-Path $jhDest $relative
            New-Item -ItemType Directory -Force -Path (Split-Path $dest -Parent) | Out-Null
            Copy-Item -LiteralPath $_.FullName -Destination $dest -Force
            Add-WasmPathWithParents ("JHOnlineData/" + $relative)
        }
}

$aliasLines = New-Object System.Collections.Generic.List[string]
$aliasLines.Add("/* Generated by scripts/prepare-wasm-assets.ps1. */") | Out-Null
$aliasLines.Add("typedef struct vm_wasm_path_alias {") | Out-Null
$aliasLines.Add("    const char *gbk;") | Out-Null
$aliasLines.Add("    const char *utf8;") | Out-Null
$aliasLines.Add("} vm_wasm_path_alias;") | Out-Null
$aliasLines.Add("static const vm_wasm_path_alias g_wasm_path_aliases[] = {") | Out-Null
foreach ($entry in $aliasEntries) {
    $aliasLines.Add($entry) | Out-Null
}
$aliasLines.Add("};") | Out-Null
$aliasLines.Add("static const int g_wasm_path_alias_count = (int)(sizeof(g_wasm_path_aliases) / sizeof(g_wasm_path_aliases[0]));") | Out-Null
[System.IO.File]::WriteAllLines($aliasFile, $aliasLines, $utf8Encoding)
